#!/bin/bash
#kill all running tasks
/var/www/sync/stopall

#set efx
EFX=none

#start video live feed & turn off Auto-Exposure and Auto-Color

raspivid -t 0 -vf --exposure backlight  --exposure fixedfps --awb fluorescent


