#!/bin/bash

#customfunction1
#put your custom code in here
#if you write something, please contribute to PocketVJ!

#this example stops all running tasks, starts this PVJ as videomaster and all slaves as videoslave with the ip

#kill all running tasks on this PVJ
/var/www/sync/stopall &

#kill all running tasks on the 7 slaves
curl -s http://192.168.1.101/backend.php/?action=stop &
curl -s http://192.168.1.102/backend.php/?action=stop &
curl -s http://192.168.1.103/backend.php/?action=stop &
curl -s http://192.168.1.104/backend.php/?action=stop &
curl -s http://192.168.1.105/backend.php/?action=stop &
curl -s http://192.168.1.106/backend.php/?action=stop &
curl -s http://192.168.1.107/backend.php/?action=stop &

#start this PVJ as master
/usr/bin/omxplayer-sync -mu -o both /media/internal/video/* > /dev/null 2>&1 & echo $! &

#start slaves as slaves
curl -s http://192.168.1.101/backend.php/?action=startslave &
curl -s http://192.168.1.102/backend.php/?action=startslave &
curl -s http://192.168.1.103/backend.php/?action=startslave &
curl -s http://192.168.1.104/backend.php/?action=startslave &
curl -s http://192.168.1.105/backend.php/?action=startslave &
curl -s http://192.168.1.106/backend.php/?action=startslave &
curl -s http://192.168.1.107/backend.php/?action=startslave &

# "I hope this works...." - Marc ;  "Oh it works." -Cornelius
