#!/bin/bash

#launchmapper is used when not booted in mapper mode to force mouse
sudo /var/www/sync/stopall &

#/home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example -f &

#the two lines are not needed i guess...
#rm /dev/input/by-id/usb-046a_0023-event-kbd
#rm /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd

sleep 1

/opt/fsaysuinput </dev/null &
ln -s /dev/input/event1 /dev/input/by-id/usb-046a_0023-event-kbd &
ln -s /dev/input/event1 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0$

/home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example -f &