#!/bin/bash

#this script exorts the mapper settings to /media/internal/mappersettings.xml
#made for PVJ 2.0

sudo killall -9 /home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example > /dev/null 2>&1

sleep 0.5

sudo /var/www/sync/stopall &

sudo cp /media/internal/mappersets/mappersetting1.xml /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/ofxpimapper.xml

sleep 0.5

/home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example -f &