#!/bin/bash

#this script exorts the mapper settings to /media/internal/mappersettings.xml
#first save then export

sudo /var/www/sync/mappers

sudo cp /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/surfaces.xml /media/internal/mappersets/mappersetting2.xml