#!/bin/bash

expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
expect /var/www/sync/mapperlefte > /dev/null 2>&1
