#!/bin/bash

expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1
expect /var/www/sync/mapperupe > /dev/null 2>&1