#!/bin/bash

#this script exorts the mapper settings to /media/internal/mappersettings.xml
#made for PVJ 3.1

#sudo killall -9 /home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example > /dev/null 2>&1
#sudo killall -9 /home/pi/openFrameworks/addons/ofxPiMapper/example_remote-server/./bin/example_remote-server > /dev/null 2>&1
#sudo killall -9 /home/pi/openFrameworks/addons/ofxPiMapper/example_camera/./bin/example_camera > /dev/null 2>&1

sleep 0.5

sudo cp /media/internal/mappersets/mappersetting2.xml /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/ofxpimapper.xml
sudo cp /media/internal/mappersets/mappersetting2.xml /home/pi/openFrameworks/addons/ofxPiMapper/example_remote-server/bin/data/ofxpimapper.xml
sudo cp /media/internal/mappersets/mappersetting2.xml /home/pi/openFrameworks/addons/ofxPiMapper/example_camera/bin/data/ofxpimapper.xml

sleep 0.5

#preload all the fake keyboard stuff
/opt/fsaysuinput &

#The below commands are only used if no mouse is connected,
#if this happens,keep in mind to change /dev/input/event1 to /dev/input/event0
mkdir /dev/input/by-id/
mkdir /dev/input/by-path/

#ln -s /dev/input/event0 /dev/input/by-id/usb-046a_0023-event-kbd
#ln -s /dev/input/event0 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd


ln -s /dev/input/event1 /dev/input/by-id/usb-046a_0023-event-kbd
ln -s /dev/input/event1 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd


/home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example -f &
