#!/bin/bash

#this script exorts the mapper settings to /media/internal/mappersettings.xml

#first save the comp

sudo /var/www/sync/mappers

sleep 0.2

#then export to setting

sudo cp /home/pi/openFrameworks/addons/ofxPiMapper/example/bin/data/surfaces.xml /media/internal/mappersets/mappersetting5.xml