#!/bin/bash

#define command line argument 1 as input (here it defines the scaling percentage):
SCALER=100
Xposition=0
Yposition=$1


#read current display resolution to define what is 100% of scaling
X="$(fbset | grep -o "mode \"[^\"]\+"  | grep -o "[^\"]\+$" | cut -d x -f 1)"
Y="$(fbset | grep -o "mode \"[^\"]\+"  | grep -o "[^\"]\+$" | cut -d x -f 2)"

#Define center point according current resolution
Xcenter="$(($X / 2))"
Ycenter="$(($Y / 2))"

#what would be the video size according to scaler input
VsizeX="$(($X * $SCALER / 100))"
VsizeY="$(($Y * $SCALER / 100))"
VsizeXhalf="$(($VsizeX / 2))"
VsizeYhalf="$(($VsizeY / 2))"

#since I dont know how to divide a result within a task, I just made 2 variables 
X1pre="$(($X - $VsizeX))"
Y1pre="$(($Y - $VsizeY))"

#the first point of the drawn video
#X1="$(($X1pre / 2))"
#Y1="$(($Y1pre / 2))"
X1="$(($Xcenter - $VsizeXhalf + $Xposition ))"
Y1="$(($Ycenter - $VsizeYhalf + $Yposition ))"

#the second point of the drawn video
#X2="$(($X1 + $VsizeX))"
#Y2="$(($Y1 + $VsizeY))"
X2="$(($Xcenter + $VsizeXhalf + $Xposition ))"
Y2="$(($Ycenter + $VsizeYhalf + $Yposition ))"

#the final command to always scale to center, zero point is top left!!:
/var/www/sync/dbuscontrol.sh setvideopos $X1 $Y1 $X2 $Y2

#write the Y position to X position script so we keep it
sudo sed -i "/Yposition=/c Yposition=$1" /var/www/sync/omxXposition 

