#!/bin/bash

/opt/fsaysuinput &
ln -s /dev/input/event1 /dev/input/by-id/usb-046a_0023-event-kbd
ln -s /dev/input/event1 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd

/home/pi/of_v0.8.4/addons/ofxPiMapper/example/./bin/example -f &