#!/bin/bash

/home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example -f &

#/var/www/sync/stopall &
#rm /dev/input/by-id/usb-046a_0023-event-kbd
#rm /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd

#sleep 1

#/opt/fsaysuinput </dev/null &>/dev/null &
#ln -s /dev/input/event1 /dev/input/by-id/usb-046a_0023-event-kbd &
#ln -s /dev/input/event1 /dev/input/by-path/platform-bcm2708_usb-usb-0:1.2.4:1.0-event-kbd &

#/var/www/sync/startmapper.sh &