#!/bin/bash

#switch to elFInder as standard filebrowser

#set extplorer to elFinder:
sudo sed -i 's#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" href="/eXtplorer/" onclick=""><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" href="/elFinder/elfinder.src.html"><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>#g' /var/www/index.php &

#set filebrowser to elFinder:
sudo sed -i 's#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" onclick="window.open(`//${window.location.hostname}:8060`)"><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" href="/elFinder/elfinder.src.html"><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>#g' /var/www/index.php &

#disable filebrowser on boot:
sudo systemctl stop filebrowser.service
sudo systemctl disable filebrowser.service



#Extplorer:
#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" href="/eXtplorer/" onclick=""><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>

#elFinder:
#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" href="/elFinder/elfinder.src.html"><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>

#filebrowser:
#<div class="col"><a class="d-xl-flex justify-content-xl-center" target="_blank" onclick="window.open(`//${window.location.hostname}:8060`)"><img class="d-xl-flex justify-content-xl-center shortcuts_header" src="assets/img/filebrowser_icon.svg" data-toggle="tooltip" title="filebrowser"></a></div>
