#!/bin/bash

#shutdown all
#put your custom code in here
#if you write something, please contribute to PocketVJ!

#This should shutdown all the players connected

#kill all running tasks on this PVJ
/var/www/sync/stopall &

#kill all running tasks on the 7 slaves
curl -s http://192.168.1.101/backend.php/?action=stop &
curl -s http://192.168.1.102/backend.php/?action=stop &
curl -s http://192.168.1.103/backend.php/?action=stop &
curl -s http://192.168.1.104/backend.php/?action=stop &
curl -s http://192.168.1.105/backend.php/?action=stop &
curl -s http://192.168.1.106/backend.php/?action=stop &
curl -s http://192.168.1.107/backend.php/?action=stop &

#shutdown slaves
curl -s http://192.168.1.101/backend.php/?action=shutdown &
curl -s http://192.168.1.102/backend.php/?action=shutdown &
curl -s http://192.168.1.103/backend.php/?action=shutdown &
curl -s http://192.168.1.104/backend.php/?action=shutdown &
curl -s http://192.168.1.105/backend.php/?action=shutdown &
curl -s http://192.168.1.106/backend.php/?action=shutdown &
curl -s http://192.168.1.107/backend.php/?action=shutdown &

#shutdown master
sudo poweroff

# "I hope this works...." - Marc ;  "Oh it works." -Cornelius
