#!/bin/bash

#kill all running tasks 
/var/www/sync/stopall


#write to .xsession that feh shall start
#sudo cp /var/www/sync/xsessionslideshow /home/pi/.xsession

#write to autostart that feh shall start
sudo cp /var/www/sync/slidestartup /home/pi/.config/lxsession/LXDE/autostart


#start x and run feh
su -s /bin/bash -c startx pi &
