#!/bin/bash

#set variable for afterslide
AFTERSLIDE=False

#kill all running tasks
/var/www/sync/stopall

if [[ $AFTERSLIDE == "True" ]]; then 
#play video without sync
/usr/bin/omxplayer --no-osd -o local /media/internal/video/05*
/var/www/sync/startimage > /dev/null &
fi

if  [[ $AFTERSLIDE == "False" ]]; then 
#play video without sync
/usr/bin/omxplayer --no-osd -o local /media/internal/video/05* > /dev/null 2>&1 & echo $! &
fi


exit 0
