#!/bin/bash

#kill all running tasks exept .mp3 player
sudo /var/www/sync/omxkill.py > /dev/null 2>&1
sudo /var/www/sync/testscreenoff.py & > /dev/null 2>&1
sudo killall -9 /home/pi/of_v0.8.4/addons/ofxPiMapper/example/./bin/example > /dev/null 2>&1
sudo killall -9 /usr/bin/TCPSClient.bin > /dev/null 2>&1
sudo /var/www/sync/rplay stop > /dev/null 2>&1
sudo killall -9 /var/www/sync/tty-clock > /dev/null 2>&1
sudo killall -9 feh > /dev/null 2>&1
sudo /var/www/sync/killxsession > /dev/null 2>&1
sudo /var/www/sync/clearscreen.sh > /dev/null 2>&1

#write to .xsession that feh shall start

sudo cp /var/www/sync/xsessionimage /home/pi/.xsession

#start x and run feh
su -s /bin/bash -c startx pi &
