#!/bin/bash

#kill all running tasks
/var/www/sync/stopall

#play vido 04 seamless looped without sync

/usr/bin/omxplayer --no-osd --loop -o local /media/internal/video/04* > /dev/null 2>&1 & echo $! &
