#!/bin/bash
#kill all running tasks
/var/www/sync/stopall

#disable hostapd hotspot 
sudo systemctl stop hostapd.service

#temporary load another /network interfaces configuration, needs /etc/network/interfaceswifi
#first shutdown interface
sudo ifdown -a --exclude=lo
#then reload new one
ifup -i /var/www/sync/interfaceswifi -a

#wait a while for all to be done and beeing initialized
sleep 10

#start video as slave with node-omxplayer-sync

node /home/pi/node-omxplayer-sync/omx-sync-wifi.js /media/internal/video/wifisync.mp4