#!/bin/bash

#kill all running tasks
/var/www/sync/stopall

#start video #!/bin/bash

#kill all running tasks
/var/www/sync/stopall

#start video 80 once
/usr/bin/omxplayer-sync -m -o both /media/internal/video/80* > /dev/null 2>&1 & echo $! &