#!/bin/bash
#kill all running tasks
/var/www/sync/stopall

#start video as slave
#remove the -o local audio flag, since this breaks sync function
/usr/bin/omxplayer-sync-old -lu /media/internal/video/* > /dev/null 2>&1 & echo $! &
