#!/bin/bash

#kill all running tasks exept slideshow
sudo /var/www/sync/omxkill.py > /dev/null 2>&1
sudo killall -9 /home/pi/openFrameworks/addons/ofxPiMapper/example/./bin/example > /dev/null 2>&1
sudo killall -9 /usr/bin/TCPSClient.bin > /dev/null 2>&1
#sudo /var/www/sync/rplay stop > /dev/null 2>&1
sudo killall -9 tty-clock > /dev/null 2>&1
sudo killall -9 mpg321 > /dev/null 2>&1
#sudo killall -9 feh > /dev/null 2>&1
#sudo kill $(pidof X) > /dev/null 2>&1
sudo killall -9 fsaysuinput > /dev/null 2>&1
sudo /var/www/sync/testscreenoff > /dev/null 2>&1
sudo killall -9 avconv > /dev/null 2>&1
sudo killall -9 pwomxplayer.bin > /dev/null 2>&1
#sudo /var/www/sync/clearscreen.sh > /dev/null 2>&1


mpg321 -l 0 /media/internal/audio/* > /dev/null 2>&1 & echo $! &