#!/bin/bash

#kill all running tasks
/var/www/sync/stopall

#play vido 12 seamless looped without sync

/usr/bin/omxplayer --no-osd --loop -o both /media/internal/video/12* > /dev/null 2>&1 & echo $! &
