#!/bin/bash

#kill all running tasks
/var/www/sync/stopall

sudo rm -f /home/pi/.xsession
sudo cp /var/www/sync/lxdeautochromium /home/pi/.config/lxsession/LXDE/autostart

#start x 
su -s /bin/bash -c startx pi &
