#!/bin/bash

#kill all running tasks
/var/www/sync/stopall

#write to autostart that qlc+ shall start
sudo cp /var/www/sync/xsessionqlcplus /home/pi/.config/lxsession/LXDE/autostart

#start x and run qlc+ as pi user
su -s /bin/bash -c startx pi &
