#!/bin/bash

if [ -z $1 ]; then
	echo "Please specify the video to start once, eg: 01";
	exit 2;
fi;

#kill all running tasks
/var/www/sync/stopall

#start video xx once
/usr/bin/omxplayer-sync -m -o both /media/internal/video/$1* > /dev/null 2>&1 & echo $! &

exit 0;