#!/bin/bash

#kill all running tasks
/var/www/sync/stopall

#play vido 07 seamless looped without sync

/usr/bin/omxplayer --no-osd --loop -o both /media/internal/video/07* > /dev/null 2>&1 & echo $! &
