#!/bin/bash

#stops slaves in the range 192.168.2.101 - 110

#kill all running tasks on this PVJ
#/var/www/sync/stopall &

#kill all running tasks on the 10 slaves
curl -s http://192.168.1.101/backend.php/?action=stop &
curl -s http://192.168.1.102/backend.php/?action=stop &
curl -s http://192.168.1.103/backend.php/?action=stop &
curl -s http://192.168.1.104/backend.php/?action=stop &
curl -s http://192.168.1.105/backend.php/?action=stop &
curl -s http://192.168.1.106/backend.php/?action=stop &
curl -s http://192.168.1.107/backend.php/?action=stop &
curl -s http://192.168.1.108/backend.php/?action=stop &
curl -s http://192.168.1.109/backend.php/?action=stop &
curl -s http://192.168.1.110/backend.php/?action=stop &

