#!/bin/bash

#update CP script:

sudo /var/www/sync/stopall
sudo cp /var/www/sync/defaulthdmi /boot/config.txt
sudo cp /var/www/sync/timer.txt /media/internal/timer.txt
sudo unzip /media/internal/PocketVJ-CP-v3-master.zip -d /media/internal/
sudo cp -r /media/internal/PocketVJ-CP-v3-master/* /var/www/
sudo chmod 755 -R /var/www/
sudo rm -r /media/internal/PocketVJ-CP-v3-master.zip
sudo rm -r /media/internal/PocketVJ-CP-v3-master
sudo chmod 755 -R /var/www
sudo chmod 777 -R /media

exit 0
