# Determine the IP address of the "eth0" network interface
export IP=`ip addr show wlan0 | grep -oP '(?<=inet )(\d+\.){3}\d+'`

# Display the IP address, so people know where to connect
wish <<END &
pack [label .ip -text "$IP:5500" -font "Helvetica 72" -fg grey -bg black]
END

# Listen for VNC connections
xvncviewer -listen -fullscreen
