# Determine the IP address of the "wlan0" network interface
export IP=`ip addr show wlan0 | grep -oP '(?<=inet )(\d+\.){3}\d+'`

# Display the IP address, so people know where to connect
wish <<END &
pack [label .ip -text "wifi VNC=> $IP:5500" -font "Helvetica 72" -fg grey -bg black]
END

# Determine the IP address of the "eth0" network interface
export IPRJ=`ip addr show eth0 | grep -oP '(?<=inet )(\d+\.){3}\d+'`


wish <<END &
pack [label .ip -text "RJ45 VNC=> $IPRJ:5500" -font "Helvetica 72" -fg grey -bg black]
END


# Listen for VNC connections
xvncviewer -listen -fullscreen -x11cursor -nocursorshape
